### ISSUE TITLE
Correct linting errors

### ISSUE THREAD

**Issue by acrosman** [acrosman/fastdog#2]
There are a number of linting errors in some of the parser modules that need to be corrected.

**Comment by gfranco93** [comment]
I'm working on this

**Comment by gfranco93** [comment]
I didn't encounter any linting errors, only in `electron.js`

**Comment by AlexandreResende** [comment]
Corrected the lint erros on electron.js.

**Comment by acrosman** [comment]
PR #6 has been merged and fixes electron.js, but there are errors in two of the files under parsers.  You should be able to get those to come up via eslint with:

`eslint --ignore-path .gitignore .`  or `eslint --ignore-path .gitignore parsers`
